/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Class.pasien;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class create extends javax.swing.JFrame {
//    int xx,xy;
    public String id;
    public String namaDepan;
    public String namaBelakang;
    public int noTelepon;
    public int noKerabat;
    public String tanggalLahir;
    public String tanggalPeriksa;
    public String jenisKelamin;
    public String alamat;
    public static String idAdmin;
    
    

    

    /**
     * Creates new form create
     */
    public create(String idAdmin) {
        initComponents();
        this.idAdmin = idAdmin;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insertbtn = new javax.swing.JButton();
        namabelakangbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tglperiksabox = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        namadepanbox = new javax.swing.JTextField();
        jeniskelaminbox = new javax.swing.JComboBox<>();
        noteleponbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tgllahirbox = new javax.swing.JTextField();
        nokerabatbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alamatbox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 210, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 80, 20));

        jLabel3.setText("No Kerabat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 20));

        jLabel4.setText("Tgl Periksa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, 20));

        insertbtn.setText("INSERT");
        insertbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertbtnMouseClicked(evt);
            }
        });
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        getContentPane().add(insertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 100, 20));

        namabelakangbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabelakangboxActionPerformed(evt);
            }
        });
        getContentPane().add(namabelakangbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 210, -1));

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, 20));

        jLabel5.setText("Nama Depan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 20));

        jLabel6.setText("No Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 20));

        tglperiksabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglperiksaboxActionPerformed(evt);
            }
        });
        getContentPane().add(tglperiksabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, -1));

        backbtn.setText("BACK");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 80, -1));

        jLabel8.setText("Nama Belakang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 90, 20));

        namadepanbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namadepanboxActionPerformed(evt);
            }
        });
        getContentPane().add(namadepanbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jeniskelaminbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - laki", "Perempuan" }));
        jeniskelaminbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeniskelaminboxActionPerformed(evt);
            }
        });
        getContentPane().add(jeniskelaminbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        noteleponbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteleponboxActionPerformed(evt);
            }
        });
        getContentPane().add(noteleponbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, -1));

        jLabel9.setText("Tgl Lahir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 70, 20));

        tgllahirbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgllahirboxActionPerformed(evt);
            }
        });
        getContentPane().add(tgllahirbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, -1));

        nokerabatbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokerabatboxActionPerformed(evt);
            }
        });
        getContentPane().add(nokerabatbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, -1));

        jLabel10.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        jLabel11.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        alamatbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatboxActionPerformed(evt);
            }
        });
        getContentPane().add(alamatbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 210, -1));

        jLabel12.setText("Jenis Kelamin");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namabelakangboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabelakangboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabelakangboxActionPerformed

    private void tglperiksaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglperiksaboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglperiksaboxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Admindashboard dasbor = new Admindashboard(idAdmin, id);
        dasbor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        
    }//GEN-LAST:event_backbtnMouseClicked

    private void namadepanboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadepanboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadepanboxActionPerformed

    private void jeniskelaminboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniskelaminboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeniskelaminboxActionPerformed

    private void noteleponboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteleponboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteleponboxActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
       
        
        pasien insertpasien = new pasien(id, namaDepan, namaBelakang, namaDepan, alamat, tanggalLahir, tanggalPeriksa, jenisKelamin, alamat);
        
        insertpasien.id = idbox.getText();
        insertpasien.namaDepan = namadepanbox.getText();
        insertpasien.namaBelakang = namabelakangbox.getText();
        
        insertpasien.noTelepon = noteleponbox.getText();
        insertpasien.noKerabat = nokerabatbox.getText();
        insertpasien.tanggalLahir = tgllahirbox.getText();
        insertpasien.tanggalPeriksa = tglperiksabox.getText();
        insertpasien.jenisKelamin = String.valueOf(jeniskelaminbox.getSelectedItem());
        insertpasien.alamat = alamatbox.getText();
        
        if (insertpasien.create(idAdmin)){
            JOptionPane.showMessageDialog(rootPane, "data ditambahkan");
            namadepanbox.setText("");
            namabelakangbox.setText("");
            noteleponbox.setText("");
            nokerabatbox.setText("");
            tgllahirbox.setText("");
            tglperiksabox.setText("");
            jeniskelaminbox.setSelectedItem("pilih");
            idbox.setText("");
        }else if (namadepanbox.equals("")) {
            namadepanbox = null;
            

        }
            

        
        
    }//GEN-LAST:event_insertbtnActionPerformed

    private void tgllahirboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgllahirboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgllahirboxActionPerformed

    private void nokerabatboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokerabatboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nokerabatboxActionPerformed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void insertbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insertbtnMouseClicked

    private void alamatboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create(idAdmin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jeniskelaminbox;
    private javax.swing.JTextField namabelakangbox;
    private javax.swing.JTextField namadepanbox;
    private javax.swing.JTextField nokerabatbox;
    private javax.swing.JTextField noteleponbox;
    private javax.swing.JTextField tgllahirbox;
    private javax.swing.JTextField tglperiksabox;
    // End of variables declaration//GEN-END:variables
}
