/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author user
 */
public class guiStart extends javax.swing.JFrame {
    static String idAdmin;
    static String dokterid;
    /**
     * Creates new form guiStart
     */
    public guiStart(String dokterid) {
        initComponents();
        this.idAdmin = idAdmin;
        this.dokterid = dokterid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goadmin = new javax.swing.JButton();
        godoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goadmin.setText("LOGIN ADMIN");
        goadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goadminActionPerformed(evt);
            }
        });
        getContentPane().add(goadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 130, -1));

        godoctor.setText("LOGIN DOCTOR");
        godoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godoctorActionPerformed(evt);
            }
        });
        getContentPane().add(godoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goadminActionPerformed
       LoginAdmin logadmin = new LoginAdmin(idAdmin, dokterid);
       logadmin.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_goadminActionPerformed

    private void godoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godoctorActionPerformed
        LoginDokter logdoctor = new LoginDokter();
        logdoctor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_godoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiStart(dokterid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goadmin;
    private javax.swing.JButton godoctor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
