/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import Class.JadwalKunjungan;
import Database.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class jadwalcrud extends javax.swing.JFrame {
    static String idAdmin;
    static String dokterid;
    static String kodedokter;
    Database db = new Database();
    /**
     * Creates new form jadwalcrud
     */
    public jadwalcrud(String idAdmin, String dokterid, String kodedokter) {
        initComponents();
        this.idAdmin = idAdmin;
        this.dokterid = dokterid;
        this.kodedokter = kodedokter;
        
    }

    private jadwalcrud() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kunjungantbl = new javax.swing.JTable();
        iddokter = new javax.swing.JTextField();
        hapuskunjunganbox = new javax.swing.JTextField();
        waktukunjunganbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        namapasienbox1 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        kodekunjunganbox1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kunjungantbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode kunjungan", "nama pasien", "waktu kunjungan"
            }
        ));
        jScrollPane1.setViewportView(kunjungantbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 680, 140));

        iddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddokterActionPerformed(evt);
            }
        });
        getContentPane().add(iddokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 30));
        getContentPane().add(hapuskunjunganbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 100, 30));
        getContentPane().add(waktukunjunganbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 100, 30));

        jLabel2.setText("NAMA PASIEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 30));

        jLabel3.setText("WAKTU KUNJUNGAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 30));

        jLabel4.setText("KODE KUNJUNGAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, 30));

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 90, -1));

        jButton2.setText("BUAT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));
        getContentPane().add(namapasienbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, 30));

        back.setText("KEMBALI");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        kodekunjunganbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodekunjunganbox1ActionPerformed(evt);
            }
        });
        getContentPane().add(kodekunjunganbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, 30));

        jLabel5.setText("ID DOKTER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Poppins (5).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JadwalKunjungan tambah = new JadwalKunjungan(idAdmin, idAdmin, idAdmin,kodedokter);
        tambah.kodeJadwal = iddokter.getText();
        tambah.namaPasien = namapasienbox1.getText();
        tambah.waktuKunjungan = waktukunjunganbox.getText();
        String getid = iddokter.getText();
        String kodedokter = getid;
        
        if(tambah.create(idAdmin, dokterid, kodedokter)){
            JOptionPane.showMessageDialog(rootPane, "jadwal baru ditambahkan");
            iddokter.setText("");
            namapasienbox1.setText("");
            waktukunjunganbox.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JadwalKunjungan hapus = new JadwalKunjungan(idAdmin, idAdmin, idAdmin, kodedokter);
        hapus.kodeJadwal = hapuskunjunganbox.getText();
        if(hapus.delete()){
            JOptionPane.showMessageDialog(rootPane, "Jadwal Dihapus");
            hapuskunjunganbox.setText("");
        }else{
            JOptionPane.showMessageDialog(rootPane, "kode kunjungan tidak ditemukan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Admindashboard back = new Admindashboard(idAdmin, dokterid);
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection connection = db.openConnection();  
        String sql = "select * from jadwal_kunjungan";
        try{
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = ( DefaultTableModel)kunjungantbl.getModel();
            while (rs.next()){
                model.addRow((new String[]{rs.getString(1), rs.getString(2), rs.getString(3)}));
            }
        }catch(SQLException ex){
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void iddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddokterActionPerformed

    private void kodekunjunganbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodekunjunganbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodekunjunganbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwalcrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwalcrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwalcrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwalcrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jadwalcrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField hapuskunjunganbox;
    private javax.swing.JTextField iddokter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodekunjunganbox1;
    private javax.swing.JTable kunjungantbl;
    private javax.swing.JTextField namapasienbox1;
    private javax.swing.JTextField waktukunjunganbox;
    // End of variables declaration//GEN-END:variables
}
