/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import Class.pasien;
import java.sql.*;
import Database.Database;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class update extends javax.swing.JFrame {
    Database data = new Database();
    pasien psienobj;
    public String id;
    public String namaDepan;
    public String namaBelakang;
    public String noTelepon;
    public String tanggalLahir;
    public String tanggalPeriksa;
    public String jenisKelamin;
    public String noKerabat;
    public String alamat;
    public static String idAdmin;
//    
    /**
     * Creates new form update
     */
    public update(String idAdmin) {
        this.psienobj = new pasien(id, namaDepan, namaBelakang, namaDepan, alamat, tanggalLahir, tanggalPeriksa, jenisKelamin, alamat);
        initComponents();
        this.idAdmin = idAdmin;
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pasientbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alamatbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nokerabatbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namabelakangbox = new javax.swing.JTextField();
        tgllahirbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglperiksabox = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        namadepanbox = new javax.swing.JTextField();
        noteleponbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jeniskelaminbox = new javax.swing.JComboBox<>();
        updatebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pasientbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PASIEN", "NAMA DEPAN","NAMA BELAKANG", "NO TELEPON", "NO KERABAT",  "ALAMAT", "JENIS KELAMIN","TANGGAL LAHIR", "TANGGAL PERIKSA"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }

        }
    );
    pasientbl.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            pasientblMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(pasientbl);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 680, 100));

    jLabel2.setText("ID");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

    idbox.setEditable(false);
    idbox.setFocusable(false);
    idbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            idboxActionPerformed(evt);
        }
    });
    getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 20));

    jLabel3.setText("JENIS KELAMIN");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 110, 20));

    alamatbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            alamatboxActionPerformed(evt);
        }
    });
    getContentPane().add(alamatbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 140, 20));

    jLabel4.setText("NAMA BELAKANG");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 100, 20));
    getContentPane().add(nokerabatbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 140, -1));

    jLabel5.setText("NO KERABAT");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 70, 20));

    jLabel6.setText("ALAMAT");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, 20));
    getContentPane().add(namabelakangbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 140, 20));
    getContentPane().add(tgllahirbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 140, 20));

    jLabel7.setText("TGL LAHIR");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 100, 20));

    jLabel8.setText("TGL PERIKSA");
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, 20));

    tglperiksabox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tglperiksaboxActionPerformed(evt);
        }
    });
    getContentPane().add(tglperiksabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 140, 20));

    backbtn.setText("Back");
    backbtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backbtnActionPerformed(evt);
        }
    });
    getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, -1));

    jLabel9.setText("NAMA DEPAN");
    getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 20));

    namadepanbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            namadepanboxActionPerformed(evt);
        }
    });
    getContentPane().add(namadepanbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 140, 20));
    getContentPane().add(noteleponbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 140, 20));

    jLabel10.setText("NO TELEPON");
    getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 70, 20));

    jeniskelaminbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
    jeniskelaminbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jeniskelaminboxActionPerformed(evt);
        }
    });
    getContentPane().add(jeniskelaminbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

    updatebtn.setText("Update");
    updatebtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            updatebtnActionPerformed(evt);
        }
    });
    getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 80, 30));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update (2).png"))); // NOI18N
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void alamatboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatboxActionPerformed

    private void tglperiksaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglperiksaboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglperiksaboxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Admindashboard dasbor = new Admindashboard(idAdmin, id);
        dasbor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection connection = data.openConnection();  
        String sql = "select * from pasien";
        try{
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)pasientbl.getModel();
            while (rs.next()){
                model.addRow((new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)}));
            }
        }catch(SQLException ex){
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jeniskelaminboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniskelaminboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeniskelaminboxActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed

        int index = pasientbl.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(rootPane, "pilih data yang ingin diupdate ");
        }else{
            
            
            pasien update = new pasien(id, namaDepan, namaBelakang, noTelepon, noKerabat, tanggalLahir, tanggalPeriksa, jenisKelamin, alamat);
            
            
            
            
            
            
            
            update.id = (String)pasientbl.getValueAt(index, 0);
            update.namaDepan = namadepanbox.getText();
            update.namaBelakang = namabelakangbox.getText();
            update.noTelepon = noteleponbox.getText();
            update.noKerabat = nokerabatbox.getText();
            update.tanggalLahir = tgllahirbox.getText();
            update.tanggalPeriksa = tglperiksabox.getText();
            update.jenisKelamin = String.valueOf(jeniskelaminbox.getSelectedItem());
            update.alamat = alamatbox.getText();
            if(update.update()){
                JOptionPane.showMessageDialog(rootPane, "data diupdate");
            }
        }
//        
            
    }//GEN-LAST:event_updatebtnActionPerformed

    private void namadepanboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadepanboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadepanboxActionPerformed

    private void pasientblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasientblMouseClicked
        int index = pasientbl.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(rootPane, "kntl");
        }else{
            String id = (String) pasientbl.getValueAt(index, 0);
            pasien pasienn = psienobj.returnValueById(id);
            idbox.setText(pasienn.getId());
            namadepanbox.setText(pasienn.getNamaDepan());
            namabelakangbox.setText(pasienn.getNamaBelakang());
            noteleponbox.setText(pasienn.getNoTelepon());
            nokerabatbox.setText(pasienn.getNoKerabat());
            tgllahirbox.setText(pasienn.getTanggalLahir());
            tglperiksabox.setText(pasienn.getTanggalPeriksa());
            jeniskelaminbox.setSelectedItem(pasienn.getJenisKelamin());
            alamatbox.setText(pasienn.getAlamat());
        }
//        
        
        
    }//GEN-LAST:event_pasientblMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update(idAdmin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jeniskelaminbox;
    private javax.swing.JTextField namabelakangbox;
    private javax.swing.JTextField namadepanbox;
    private javax.swing.JTextField nokerabatbox;
    private javax.swing.JTextField noteleponbox;
    private javax.swing.JTable pasientbl;
    private javax.swing.JTextField tgllahirbox;
    private javax.swing.JTextField tglperiksabox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
